apiVersion: v1
kind: Namespace
metadata:
  name: homepage
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage
  namespace: homepage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homepage
rules:
  - apiGroups: [""]
    resources: ["namespaces", "pods", "nodes", "services", "persistentvolumes", "persistentvolumeclaims"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
    verbs: ["get", "list"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes", "pods"]
    verbs: ["get", "list"]
  - nonResourceURLs: ["/version", "/healthz", "/metrics"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homepage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: homepage
subjects:
  - kind: ServiceAccount
    name: homepage
    namespace: homepage
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  settings.yaml: |
    title: "Homelab Dashboard"
    favicon: https://github.com/gethomepage/homepage/raw/main/public/android-chrome-192x192.png
    theme: dark
    color: slate
    headerStyle: boxed
    target: _self
    useEqualHeights: true
    layout:
      Monitoring:
        style: row
        columns: 2
      Infrastructure:
        style: row
        columns: 3
      Management:
        style: row
        columns: 2

  services.yaml: |
    - Monitoring:
        - Prometheus:
            href: https://prometheus.elam.sh
            description: Metrics Collection & Monitoring
            icon: prometheus.png
            ping: https://prometheus.elam.sh
            widget:
              type: prometheus
              url: https://prometheus.elam.sh
        - Grafana:
            href: https://grafana.elam.sh
            description: Metrics Visualization & Dashboards
            icon: grafana.png
            ping: https://grafana.elam.sh

    - Infrastructure:
        - ArgoCD:
            href: https://argo.elam.sh
            description: GitOps Management
            icon: argocd.png
            ping: https://argo.elam.sh
        - Rancher:
            href: https://rancher.elam.sh
            description: Kubernetes Management
            icon: rancher.png
            ping: https://rancher.elam.sh
        - Homepage:
            href: https://homepage.elam.sh
            description: This Dashboard
            icon: homepage.png

    - Management:
        - System Monitor:
            widget:
              type: kubernetes
              cluster:
                show: true
                cpu: true
                memory: true
                showLabel: true
                label: "RKE2 Cluster"
              nodes:
                show: true
                cpu: true
                memory: true
                showLabel: true
        - Cluster Metrics:
            widget:
              type: customapi
              url: https://prometheus.elam.sh/api/v1/query?query=count(up==1)
              mappings:
                - field: data.result.0.value.1
                  label: Services Up
                  format: number
                  suffix: " targets"

  widgets.yaml: |
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - datetime:
        text_size: xl
        format:
          timeStyle: short
          dateStyle: short
          hourCycle: h23
    - openmeteo:
        label: Weather
        latitude: 35.025
        longitude: -89.263
        timezone: America/Chicago
        units: imperial
        cache: 5

  bookmarks.yaml: |
    - Monitoring:
        - Dashboards:
            - abbr: Node
              href: https://grafana.elam.sh/d/xfpJB9FGz/node-exporter-dashboard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homepage-config
  namespace: homepage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
  labels:
    app: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      serviceAccountName: homepage
      containers:
      - name: homepage
        image: ghcr.io/gethomepage/homepage:latest
        ports:
        - containerPort: 3000
        env:
        - name: HOMEPAGE_CONFIG_DIR
          value: /app/config
        - name: HOMEPAGE_ALLOWED_HOSTS
          value: "*"
        - name: LOG_LEVEL
          value: debug
        - name: HOMEPAGE_VAR_TITLE
          value: "Homelab Dashboard"
        volumeMounts:
        - name: config
          mountPath: /app/config
        - name: config-files
          mountPath: /app/config/settings.yaml
          subPath: settings.yaml
        - name: config-files
          mountPath: /app/config/services.yaml
          subPath: services.yaml
        - name: config-files
          mountPath: /app/config/widgets.yaml
          subPath: widgets.yaml
        - name: config-files
          mountPath: /app/config/bookmarks.yaml
          subPath: bookmarks.yaml
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: homepage-config
      - name: config-files
        configMap:
          name: homepage-config
---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: homepage
spec:
  selector:
    app: homepage
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
  namespace: homepage
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-set-headers: "homepage/homepage-headers"
spec:
  ingressClassName: nginx
  rules:
  - host: homepage.elam.sh
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homepage
            port:
              number: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-headers
  namespace: homepage
data:
  X-Forwarded-Proto: https
  X-Forwarded-Host: homepage.elam.sh