apiVersion: v2
name: monitoring
description: Monitoring stack for homelab
type: application
version: 0.1.0

dependencies:
  - name: kube-prometheus-stack
    version: "67.2.0"
    repository: https://prometheus-community.github.io/helm-charts
