kube-prometheus-stack:
  prometheusOperator:
    admissionWebhooks:
      enabled: false
    tls:
      enabled: false
  
  grafana:
    adminPassword: admin
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - grafana.elam.sh
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
    
    # Enable persistence - this is the key change
    persistence:
      enabled: true
      storageClassName: local-path
      size: 1Gi
      accessModes:
        - ReadWriteOnce
  
  prometheus:
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - prometheus.elam.sh
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
    prometheusSpec:
      # Also enable Prometheus persistence
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: local-path
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 5Gi
      retention: 30d
  
  alertmanager:
    enabled: false
  nodeExporter:
    enabled: true
  kubeStateMetrics:
    enabled: true