apiVersion: v2
name: longhorn
description: Cloud native distributed block storage for Kubernetes
type: application
version: 0.1.0

dependencies:
  - name: longhorn
    version: "1.7.2"
    repository: https://charts.longhorn.io
