apiVersion: v2
name: local-path-provisioner
description: Local path provisioner for Kubernetes
type: application
version: 0.1.0

dependencies:
  - name: local-path-provisioner
    version: "0.0.30"
    repository: https://charts.rancher.io
