apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - local-path-provisioner.yaml

patches:
  - target:
      kind: StorageClass
      name: local-path
    patch: |-
      - op: add
        path: /metadata/annotations/storageclass.kubernetes.io~1is-default-class
        value: "true"
