local-path-provisioner:
  # Set as default storage class
  storageClass:
    defaultClass: true
    name: local-path
  
  # Configure path on nodes
  configmap:
    setup: |-
      #!/bin/sh
      set -eu
      mkdir -m 0777 -p "$1"
    teardown: |-
      #!/bin/sh
      set -eu
      rm -rf "$1"
    helperPod: |-
      apiVersion: v1
      kind: Pod
      metadata:
        name: helper-pod
      spec:
        containers:
        - name: helper-pod
          image: busybox
          imagePullPolicy: IfNotPresent
  
  nodePathMap:
    - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
      paths:
        - /var/lib/rancher/k3s/storage
