grafana:
  # Reference existing secret instead of setting password directly
  admin:
    existingSecret: grafana
    userKey: admin-user
    passwordKey: admin-password
  
  # Disable the leaked secrets validation
  assertNoLeakedSecrets: false
  
  # Persistence for dashboards and data
  persistence:
    enabled: true
    storageClassName: local-path
    size: 2Gi
    accessModes:
      - ReadWriteOnce
  
  # Ingress configuration
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.elam.sh
    path: /
    pathType: Prefix
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
  
  # Resources
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  
  # Service account
  serviceAccount:
    create: true
    name: grafana
  
  # Basic configuration
  grafana.ini:
    server:
      root_url: "https://grafana.elam.sh"
      serve_from_sub_path: false
    users:
      allow_sign_up: false
      auto_assign_org: true
      auto_assign_org_role: Viewer
    auth.anonymous:
      enabled: false
  
  # Data sources
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: TestData
        type: testdata
        access: proxy
        isDefault: true
